#!/bin/bash

# PB - generated by AI to extract the git hash of the MKL_jll outside of Docker
# build so that changes to Manifest/Project toml do not force a recompile of the
# MKL_jll layer unless the dependency actually changes 

# Check if Manifest.toml exists
if [ ! -f "Manifest.toml" ]; then
    echo "Error: Manifest.toml not found in current directory"
    exit 1
fi

# Extract the UUID for MKL_jll using awk and trim any whitespace
# Look for the MKL_jll section and then find the uuid line
# Extract just the UUID part between the quotes and ensure no trailing newline
awk '/\[\[deps\.MKL_jll\]\]/{flag=1;next}/\[\[/{if(flag){exit}}flag&&/uuid/{gsub(/^.*= "|".*$/,"",$0);printf "%s", $0}' Manifest.toml > MKL_jll.dep

# Check if we found and extracted the UUID
if [ ! -s MKL_jll.dep ]; then
    echo "Error: Could not find MKL_jll UUID in Manifest.toml"
    rm MKL_jll.dep
    exit 1
fi

echo "Successfully extracted MKL_jll UUID to MKL_jll.dep"