@baseUrl = {{$dotenv API_BASE_URL}}
@webBaseUrl = {{$dotenv REST_API_BASE_URL}}
@contentType = application/json

### Login to rest API

### Register a new user
# @name register
POST {{webBaseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "securepassword123"
}

### Login with the registered user
# @name login
POST {{webBaseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "securepassword123"
}

###
@authToken = {{login.response.body.token}}

### Hello world (authorised)
# @name loadEnv
GET {{baseUrl}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

### Hello world (no auth)
# @name loadEnv
GET {{baseUrl}}
Content-Type: {{contentType}}

### Health chgeck
GET {{baseUrl}}/health
Content-Type: : {{contentType}}

### Example of 500 internal error

GET {{baseUrl}}/tile/10/928/560?region=Townsville-Whitsunday&rtype=slopes&Depth=-10%3A0&Slope=0%3A45&Turbidity=0%3A60&WavesHs=0%3A1&WavesTp=0%3A6
Content-Type: : {{contentType}}
Authorization: Bearer {{authToken}}